### ISSUE TITLE
Homing algorithm needs to be updated

### ISSUE THREAD

**Issue by BScatterplot** [Binary-Coalescence/motorDSM#3]
The MD90 driver doesn't currently accept an argument for Home direction- it just goes in the last direction it was told to. The homing algorithm should update as follows:

1- SNS 5 (some small number of steps)
2- ESF (if homing forward, or ESB if homing reverse)
3- Wait for steps to execute
4- Issue HOM command

Wait time should be 1.2 * (5/(HVEL*100))

_(1.2 is a 20% extra wait just in case, 5 is the number of steps to take, and 100 is the conversion based on a 10 µm step size. So, if HVAL is 1mm/s, then step frequency is 100 Hz, so 5 steps is 5/100 = 50 ms, x1.2 =  60 ms wait._

**Comment by djsissom** [comment]
Is something upside down on the sleep time here?  Just making sure the units cancel out gives:

    sleepTime = SLEEP_MARGIN * SMALL_NSTEPS * COUNTS_PER_STEP / maxVelocity;

for SLEEP_MARGIN = 1.2, SMALL_NSTEPS = 5, and COUNTS_PER_STEP = 1000 to give sleepTime in seconds.  The velocity passed to the home routine is in encoder counts per second.

**Comment by BScatterplot** [comment]
I think that's all correct; you end up with "seconds". I assume "maxVelocity" is the homing velocity (aka HVEL converted to encoder counts per second), is that right?

Example math:

HVEL = 1.0 mm/s = 1,000 µm/s = 1,000,000 nm/s = 100,000 enc counts/sec  
Step size = 10 µm/step = 10,000 nm/step = 1,000 enc counts/step
Wait time = 1.2 * 5 steps * 1,000 enc counts/step * (sec/100,000 enc counts) = 0.06 seconds = 60 ms

That looks correct to me.
