### ISSUE TITLE
Check Tweak distance

### ISSUE THREAD

**Issue by BScatterplot** [Binary-Coalescence/motorDSM#6]
The setup script sets the "TWV" values- this should be checked for functionality

**Comment by djsissom** [comment]
I don't see anywhere in the motor base classes that would give us anything to call for tweaking position ourselves.  We should check whether this works just from EPICS setting to a new position or not.  I'll delete the line if not.

**Comment by BScatterplot** [comment]
This is a function built into EPICS, doesn't need any "tweaks" for the DSM motor  ;)
